---
title: "FLYCOP results - Downstream analysis"
output:
  github_document:
    toc: true
---

# Analysis of PET degradation results - FLYCOP

---

## Reading data
```{r,warning=FALSE,results=FALSE,message=FALSE}


options(warn = -1) 
data=read.table("data.txt",sep="\t",header=TRUE,row.names = 1)
```

## Some plots
### Correlation matrix

The groups are defined by:
* PHA>3.5 = HIGH
* PHA<3.5 AND PHA > 3.0 = NORMAL
* PHA<3.0 = LOW
```{r,echo=FALSE,warning=FALSE, out.width="200%", out.height="200%",message=FALSE,results=FALSE}
library(GGally)

ggpairs(data)

```

### Correlation plot
```{r warning=FALSE, out.width="200%", out.height="200%", comment=FALSE,results=FALSE,message=FALSE}
ggcorr(data)

```

### Splitting by group


```{r,warning=FALSE,message=FALSE, out.width="200%", out.height="200%",results=FALSE}
ggpairs(data,ggplot2::aes(colour=PHA.1))

```



### Density plots

```{r,message=FALSE,warning=FALSE, out.width="200%", out.height="200%",results=FALSE}
ggpairs(
  data,
  lower = list(continuous = "density", 
               combo = "facetdensity",
               mapping=ggplot2::aes(colour=PHA.1))
)

```


### Ellipse plot

```{r,message=FALSE,warning=FALSE, out.width="200%", out.height="200%",results=FALSE}
library(ellipse)
library(RColorBrewer)
datacor=cor(data[,1:5])
my_colors <- brewer.pal(5, "Spectral")
my_colors <- colorRampPalette(my_colors)(100)
ord <- order(datacor[1, ])
data_ord <- datacor[ord, ord]
plotcorr(data_ord , col=my_colors[data_ord*50+50] , mar=c(1,1,1,1)  )

```
